# Generated by Django 4.2.23 on 2026-02-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('polygon', models.TextField(help_text='JSON list of [lat, lng] points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
