# Generated by Django 4.2.23 on 2026-03-15 01:52

from django.db import migrations, models
import django.db.models.deletion


def forward_copy_positions(apps, schema_editor):
    Employee = apps.get_model("api", "Employee")
    Position = apps.get_model("api", "Position")

    for employee in Employee.objects.all():
        name = (employee.position or "").strip()
        if not name:
            continue
        position, _ = Position.objects.get_or_create(name=name)
        employee.position_fk = position
        employee.save(update_fields=["position_fk"])


def reverse_copy_positions(apps, schema_editor):
    Employee = apps.get_model("api", "Employee")
    for employee in Employee.objects.all():
        if getattr(employee, "position_fk_id", None):
            employee.position = employee.position_fk.name
            employee.save(update_fields=["position"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_position'),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="position_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.position",
            ),
        ),
        migrations.RunPython(forward_copy_positions, reverse_copy_positions),
        migrations.RemoveField(
            model_name="employee",
            name="position",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="position_fk",
            new_name="position",
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.position"),
        ),
    ]
